import { RunApiError } from './runApi'

export type InstallationScope = 'WORKSPACE' | 'USER_GLOBAL'
export type McpToolRiskLevel = 'LOW' | 'MEDIUM' | 'HIGH'
export type McpRequiredCapability = 'CODE_READ' | 'CODE_WRITE' | 'TERMINAL' | 'BROWSER' | 'TOOL'
export type WorkspaceMountMode = 'NONE' | 'READ_ONLY' | 'READ_WRITE'
export interface OfficialMcpServer { serviceId: string; sourcePath: string; sourceUrl: string; commitSha: string; blobShas: Record<string, string>; metadataSha256: string; version: string; description: string; license: string; command: string; arguments: string[]; launchBin: string; environmentVariableNames: string[]; readmeSummary: string }
export interface McpCatalog { repository: string; commitSha: string; fetchedAt: string; expiresAt: string; etag: string; status: string; servers: OfficialMcpServer[]; errors: Record<string, string> }
export interface GitHubSkillRepository { repository: string; repositoryUrl: string; defaultBranch: string; description: string; license: string }
export interface McpPreview { previewId: string; confirmationToken: string; sourceUrl: string; commitSha: string; metadataSha256: string; command: string; arguments: string[]; environmentNames: string[]; summary: string; scope: InstallationScope; workspaceId: string | null; riskLevel: McpToolRiskLevel; requiredCapabilities: McpRequiredCapability[]; workspaceMountMode: WorkspaceMountMode; networkMode: 'NONE'; runtimeImage: string; requiresConfirmation: boolean; sideEffectFree: boolean; expiresAt: string }
export interface SkillPreview { previewId: string; confirmationToken: string; repositoryUrl: string; repository: string; commitSha: string; blobSha: string; path: 'SKILL.md'; license: string; contentSha256: string; summary: string; requestedToolNames: string[]; scope: InstallationScope; workspaceId: string | null; requiresConfirmation: boolean; sideEffectFree: boolean; expiresAt: string }
export interface McpInstallation { installationId: string; snapshotId: string; scope: InstallationScope; workspaceId: string | null; actorUserId: string; status: string; createdAt: string; confirmedAt: string; updatedAt: string; riskLevel: McpToolRiskLevel; requiredCapabilities: McpRequiredCapability[]; workspaceMountMode: WorkspaceMountMode; networkMode: 'NONE'; runtimeState: string; runtimeError: string; version: number }
export interface SkillInstallation { skillInstallationId: string; skillSnapshotId: string; scope: InstallationScope; workspaceId: string | null; actorUserId: string; status: string; createdAt: string; confirmedAt: string; updatedAt: string }

type JsonObject = Record<string, unknown>
function objectAt(value: unknown, path: string): JsonObject { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`${path} 必须是对象`); return value as JsonObject }
function exactKeys(value: JsonObject, expected: string[], path: string) { const unknown = Object.keys(value).filter((key) => !expected.includes(key)); if (unknown.length) throw new TypeError(`${path} 包含未知字段: ${unknown.join(', ')}`) }
function text(value: unknown, path: string) { if (typeof value !== 'string' || value.trim() === '') throw new TypeError(`${path} 必须是非空字符串`); return value }
function optionalText(value: unknown, path: string) { if (typeof value !== 'string') throw new TypeError(`${path} 必须是字符串`); return value }
function arrayText(value: unknown, path: string) { if (!Array.isArray(value)) throw new TypeError(`${path} 必须是数组`); return value.map((v, i) => text(v, `${path}[${i}]`)) }
function recordText(value: unknown, path: string) { const object = objectAt(value, path); return Object.fromEntries(Object.entries(object).map(([k, v]) => [text(k, `${path} key`), text(v, `${path}.${k}`)])) }
function uuidOrText(value: unknown, path: string) { return text(value, path) }
function integerAt(value: unknown, path: string) { if (typeof value !== 'number' || !Number.isInteger(value) || value < 0) throw new TypeError(`${path} 必须是非负整数`); return value }
function url(value: unknown, path: string) { const result = text(value, path); try { new URL(result) } catch { throw new TypeError(`${path} 必须是 URL`) } return result }
function requestJson(urlPath: string, init: RequestInit, fetcher: typeof fetch) { return fetcher(urlPath, init).then(async (response) => { const body = await response.text(); if (!response.ok) throw new RunApiError(`能力 API 请求失败: HTTP ${response.status}`, response.status, body); try { return JSON.parse(body) as unknown } catch (error) { throw new TypeError(`能力 API 返回了非法 JSON: ${(error as Error).message}`) } }) }

export function decodeMcpServer(value: unknown, path = 'server'): OfficialMcpServer { const o = objectAt(value, path); exactKeys(o, ['serviceId','sourcePath','sourceUrl','commitSha','blobShas','metadataSha256','version','description','license','command','arguments','launchBin','environmentVariableNames','readmeSummary'], path); return { serviceId: text(o.serviceId, `${path}.serviceId`), sourcePath: text(o.sourcePath, `${path}.sourcePath`), sourceUrl: url(o.sourceUrl, `${path}.sourceUrl`), commitSha: text(o.commitSha, `${path}.commitSha`), blobShas: recordText(o.blobShas, `${path}.blobShas`), metadataSha256: text(o.metadataSha256, `${path}.metadataSha256`), version: text(o.version, `${path}.version`), description: optionalText(o.description, `${path}.description`), license: optionalText(o.license, `${path}.license`), command: text(o.command, `${path}.command`), arguments: arrayText(o.arguments, `${path}.arguments`), launchBin: text(o.launchBin, `${path}.launchBin`), environmentVariableNames: arrayText(o.environmentVariableNames, `${path}.environmentVariableNames`), readmeSummary: optionalText(o.readmeSummary, `${path}.readmeSummary`) } }
export function decodeMcpCatalog(value: unknown): McpCatalog { const o = objectAt(value, 'catalog'); exactKeys(o, ['repository','commitSha','fetchedAt','expiresAt','etag','status','servers','errors'], 'catalog'); if (!Array.isArray(o.servers)) throw new TypeError('catalog.servers 必须是数组'); return { repository: text(o.repository, 'catalog.repository'), commitSha: text(o.commitSha, 'catalog.commitSha'), fetchedAt: optionalText(o.fetchedAt, 'catalog.fetchedAt'), expiresAt: optionalText(o.expiresAt, 'catalog.expiresAt'), etag: optionalText(o.etag, 'catalog.etag'), status: text(o.status, 'catalog.status'), servers: o.servers.map((v, i) => decodeMcpServer(v, `catalog.servers[${i}]`)), errors: recordText(o.errors, 'catalog.errors') } }
export function decodeSkillRepository(value: unknown): GitHubSkillRepository { const o = objectAt(value, 'skill'); exactKeys(o, ['repository','repositoryUrl','defaultBranch','description','license'], 'skill'); return { repository: text(o.repository, 'skill.repository'), repositoryUrl: url(o.repositoryUrl, 'skill.repositoryUrl'), defaultBranch: text(o.defaultBranch, 'skill.defaultBranch'), description: optionalText(o.description, 'skill.description'), license: optionalText(o.license, 'skill.license') } }
function decodeMcpInstallation(value: unknown, path: string): McpInstallation { const o = objectAt(value, path); exactKeys(o, ['installationId','snapshotId','scope','workspaceId','actorUserId','status','createdAt','confirmedAt','updatedAt','riskLevel','requiredCapabilities','workspaceMountMode','networkMode','runtimeState','runtimeError','version'], path); return { installationId: uuidOrText(o.installationId, `${path}.installationId`), snapshotId: uuidOrText(o.snapshotId, `${path}.snapshotId`), scope: text(o.scope, `${path}.scope`) as InstallationScope, workspaceId: o.workspaceId === null ? null : uuidOrText(o.workspaceId, `${path}.workspaceId`), actorUserId: text(o.actorUserId, `${path}.actorUserId`), status: text(o.status, `${path}.status`), createdAt: optionalText(o.createdAt, `${path}.createdAt`), confirmedAt: optionalText(o.confirmedAt, `${path}.confirmedAt`), updatedAt: optionalText(o.updatedAt, `${path}.updatedAt`), riskLevel: text(o.riskLevel, `${path}.riskLevel`) as McpToolRiskLevel, requiredCapabilities: arrayText(o.requiredCapabilities, `${path}.requiredCapabilities`) as McpRequiredCapability[], workspaceMountMode: text(o.workspaceMountMode, `${path}.workspaceMountMode`) as WorkspaceMountMode, networkMode: text(o.networkMode, `${path}.networkMode`) as 'NONE', runtimeState: text(o.runtimeState, `${path}.runtimeState`), runtimeError: optionalText(o.runtimeError, `${path}.runtimeError`), version: integerAt(o.version, `${path}.version`) } }
function decodeSkillInstallation(value: unknown, path: string): SkillInstallation { const o = objectAt(value, path); exactKeys(o, ['skillInstallationId','skillSnapshotId','scope','workspaceId','actorUserId','status','createdAt','confirmedAt','updatedAt'], path); return { skillInstallationId: uuidOrText(o.skillInstallationId, `${path}.skillInstallationId`), skillSnapshotId: uuidOrText(o.skillSnapshotId, `${path}.skillSnapshotId`), scope: text(o.scope, `${path}.scope`) as InstallationScope, workspaceId: o.workspaceId === null ? null : uuidOrText(o.workspaceId, `${path}.workspaceId`), actorUserId: text(o.actorUserId, `${path}.actorUserId`), status: text(o.status, `${path}.status`), createdAt: optionalText(o.createdAt, `${path}.createdAt`), confirmedAt: optionalText(o.confirmedAt, `${path}.confirmedAt`), updatedAt: optionalText(o.updatedAt, `${path}.updatedAt`) } }
function decodePreview(value: unknown, skill: boolean): McpPreview | SkillPreview { const o = objectAt(value, 'preview'); const base = ['previewId','confirmationToken','commitSha','summary','scope','workspaceId','requiresConfirmation','sideEffectFree','expiresAt']; for (const key of base) if (!(key in o)) throw new TypeError(`preview 缺少字段: ${key}`); if (skill) { exactKeys(o, [...base,'repositoryUrl','repository','blobSha','path','license','contentSha256','requestedToolNames'], 'preview'); return { previewId: text(o.previewId,'preview.previewId'), confirmationToken: text(o.confirmationToken,'preview.confirmationToken'), repositoryUrl: url(o.repositoryUrl,'preview.repositoryUrl'), repository: text(o.repository,'preview.repository'), commitSha: text(o.commitSha,'preview.commitSha'), blobSha: text(o.blobSha,'preview.blobSha'), path: 'SKILL.md', license: optionalText(o.license,'preview.license'), contentSha256: text(o.contentSha256,'preview.contentSha256'), summary: text(o.summary,'preview.summary'), requestedToolNames: arrayText(o.requestedToolNames,'preview.requestedToolNames'), scope: o.scope as InstallationScope, workspaceId: o.workspaceId === null ? null : text(o.workspaceId,'preview.workspaceId'), requiresConfirmation: o.requiresConfirmation === true, sideEffectFree: o.sideEffectFree === true, expiresAt: optionalText(o.expiresAt,'preview.expiresAt') } } exactKeys(o, [...base,'sourceUrl','metadataSha256','command','arguments','environmentNames','riskLevel','requiredCapabilities','workspaceMountMode','networkMode','runtimeImage'], 'preview'); return { previewId: text(o.previewId,'preview.previewId'), confirmationToken: text(o.confirmationToken,'preview.confirmationToken'), sourceUrl: url(o.sourceUrl,'preview.sourceUrl'), commitSha: text(o.commitSha,'preview.commitSha'), metadataSha256: text(o.metadataSha256,'preview.metadataSha256'), command: text(o.command,'preview.command'), arguments: arrayText(o.arguments,'preview.arguments'), environmentNames: arrayText(o.environmentNames,'preview.environmentNames'), summary: text(o.summary,'preview.summary'), scope: o.scope as InstallationScope, workspaceId: o.workspaceId === null ? null : text(o.workspaceId,'preview.workspaceId'), riskLevel: text(o.riskLevel,'preview.riskLevel') as McpToolRiskLevel, requiredCapabilities: arrayText(o.requiredCapabilities,'preview.requiredCapabilities') as McpRequiredCapability[], workspaceMountMode: text(o.workspaceMountMode,'preview.workspaceMountMode') as WorkspaceMountMode, networkMode: text(o.networkMode,'preview.networkMode') as 'NONE', runtimeImage: text(o.runtimeImage,'preview.runtimeImage'), requiresConfirmation: o.requiresConfirmation === true, sideEffectFree: o.sideEffectFree === true, expiresAt: optionalText(o.expiresAt,'preview.expiresAt') } }

export async function listMcpCatalog(fetcher: typeof fetch = globalThis.fetch) { return decodeMcpCatalog(await requestJson('/api/mcp/catalog', { method: 'GET' }, fetcher)) }
export async function searchSkills(query: string, fetcher: typeof fetch = globalThis.fetch) { if (!query.trim()) return []; const body = await requestJson(`/api/skills/search?q=${encodeURIComponent(query)}`, { method: 'GET' }, fetcher); if (!Array.isArray(body)) throw new TypeError('skills 必须是数组'); return body.map((v, i) => decodeSkillRepository(v, `skills[${i}]`)) }
export async function previewMcp(workspaceId: string, serverKey: string, scope: InstallationScope, fetcher: typeof fetch = globalThis.fetch) { return decodePreview(await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/mcp/installations/preview`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ serverKey, scope, targetWorkspaceId: scope === 'WORKSPACE' ? workspaceId : null, riskLevel: 'HIGH', requiredCapabilities: ['TOOL'], workspaceMountMode: 'NONE' }) }, fetcher), false) as McpPreview }
export async function confirmMcp(workspaceId: string, preview: McpPreview, fetcher: typeof fetch = globalThis.fetch) { return requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/mcp/installations`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ previewId: preview.previewId, confirmationToken: preview.confirmationToken, scope: preview.scope, targetWorkspaceId: preview.workspaceId }) }, fetcher) }
export async function previewSkill(workspaceId: string, repository: string, scope: InstallationScope, fetcher: typeof fetch = globalThis.fetch) { return decodePreview(await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/skills/preview`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ repository, scope, targetWorkspaceId: scope === 'WORKSPACE' ? workspaceId : null }) }, fetcher), true) as SkillPreview }
export async function confirmSkill(workspaceId: string, preview: SkillPreview, fetcher: typeof fetch = globalThis.fetch) { return requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/skills`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ previewId: preview.previewId, confirmationToken: preview.confirmationToken, scope: preview.scope, targetWorkspaceId: preview.workspaceId }) }, fetcher) }
export async function listMcpInstallations(workspaceId: string, fetcher: typeof fetch = globalThis.fetch) { const body = await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/mcp/installations`, { method: 'GET' }, fetcher); if (!Array.isArray(body)) throw new TypeError('MCP installations 必须是数组'); return body.map((value, index) => decodeMcpInstallation(value, `mcpInstallations[${index}]`)) }
export async function listSkillInstallations(workspaceId: string, fetcher: typeof fetch = globalThis.fetch) { const body = await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/skills`, { method: 'GET' }, fetcher); if (!Array.isArray(body)) throw new TypeError('Skill installations 必须是数组'); return body.map((value, index) => decodeSkillInstallation(value, `skillInstallations[${index}]`)) }
export async function prepareMcpMaterial(workspaceId: string, installation: McpInstallation, fetcher: typeof fetch = globalThis.fetch) { return decodeMcpInstallation(await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/mcp/installations/${encodeURIComponent(installation.installationId)}/material`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ expectedVersion: installation.version }) }, fetcher), 'installation') }
export async function startMcpInstallation(workspaceId: string, installation: McpInstallation, fetcher: typeof fetch = globalThis.fetch) { return decodeMcpInstallation(await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/mcp/installations/${encodeURIComponent(installation.installationId)}/start`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ expectedVersion: installation.version, targetWorkspaceId: workspaceId, environment: {} }) }, fetcher), 'installation') }
export async function stopMcpInstallation(workspaceId: string, installation: McpInstallation, fetcher: typeof fetch = globalThis.fetch) { return decodeMcpInstallation(await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/mcp/installations/${encodeURIComponent(installation.installationId)}/stop`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ expectedVersion: installation.version, targetWorkspaceId: workspaceId, environment: {} }) }, fetcher), 'installation') }
export async function uninstallMcpInstallation(workspaceId: string, installation: McpInstallation, fetcher: typeof fetch = globalThis.fetch) { return decodeMcpInstallation(await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/mcp/installations/${encodeURIComponent(installation.installationId)}?expectedVersion=${installation.version}`, { method: 'DELETE' }, fetcher), 'installation') }
export async function uninstallSkillInstallation(workspaceId: string, installation: SkillInstallation, fetcher: typeof fetch = globalThis.fetch) { return decodeSkillInstallation(await requestJson(`/api/workspaces/${encodeURIComponent(workspaceId)}/skills/${encodeURIComponent(installation.skillInstallationId)}`, { method: 'DELETE' }, fetcher), 'skillInstallation') }
