import { Pencil, Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import type { ModelConfigurationSnapshot } from '../api/contracts'
type Props = { snapshot: ModelConfigurationSnapshot; busy: boolean; onRun: (r: string, op: () => Promise<unknown>) => Promise<void>; create?: (c: any) => Promise<any>; update: (id: string, c: any) => Promise<any>; remove: (id: string) => Promise<any> }
export function ModelProviderSettingsSection({ snapshot, busy, onRun, create, update, remove }: Props) {
  const empty = { displayName: '', baseUrl: '', chatCompletionsPath: '/v1/chat/completions', apiKey: '' }; const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [pending, setPending] = useState(false); const disabled = busy || pending
  const save = (e: FormEvent) => { e.preventDefault(); if (disabled) return; setPending(true); void onRun('provider', async () => { if (editing) { const { apiKey, ...base } = form; await update(editing, { ...base, ...(apiKey.trim() ? { apiKey } : {}) }) } else { if (!create) throw new Error('模型 Provider 接口未配置'); await create(form) }; setEditing(null); setForm(empty) }).finally(() => setPending(false)) }
  return <section className="model-settings-section"><h3>Provider</h3>{snapshot.providers.map((p) => <div className="model-resource-row" key={p.providerId}><div><strong>{p.displayName}</strong><span>{p.baseUrl}{p.chatCompletionsPath} · {p.apiKeyMasked}</span></div><div><button type="button" aria-label={`编辑 Provider ${p.displayName}`} title="编辑" disabled={disabled} onClick={() => { setEditing(p.providerId); setForm({ displayName: p.displayName, baseUrl: p.baseUrl, chatCompletionsPath: p.chatCompletionsPath, apiKey: '' }) }}><Pencil size={14} /></button><button type="button" aria-label={`删除 Provider ${p.displayName}`} title="删除" disabled={disabled} onClick={() => { if (window.confirm(`确认删除 Provider ${p.displayName}？`)) { setPending(true); void onRun('provider', () => remove(p.providerId)).finally(() => setPending(false)) } }}><Trash2 size={14} /></button></div></div>)}<form onSubmit={save}><h4>{editing ? '编辑 Provider' : '新增 Provider'}</h4><input disabled={disabled} aria-label="Provider 名称" required value={form.displayName} onChange={e => setForm({ ...form, displayName: e.target.value })} /><input disabled={disabled} aria-label="API Base URL" required value={form.baseUrl} onChange={e => setForm({ ...form, baseUrl: e.target.value })} /><input disabled={disabled} aria-label="Chat Completions 路径" required value={form.chatCompletionsPath} onChange={e => setForm({ ...form, chatCompletionsPath: e.target.value })} /><input disabled={disabled} aria-label="Provider API Key" type="password" required={!editing} value={form.apiKey} onChange={e => setForm({ ...form, apiKey: e.target.value })} /><button type="submit" disabled={disabled}><Plus size={14} />{editing ? '保存 Provider' : '新增 Provider'}</button></form></section>
}
